"""Added scheduled_interval in DagenDagVersion

Revision ID: 8c49f26edb50
Revises: db3d3cc79285
Create Date: 2020-07-19 17:42:30.931469

"""
from alembic import op
import sqlalchemy as sa
import airflow
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c49f26edb50'
down_revision = 'db3d3cc79285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dagen_dag_version', sa.Column(
        'schedule_interval', sa.String(50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dagen_dag_version', 'schedule_interval')
    # ### end Alembic commands ###
