"""Added initial models

Revision ID: b7b25fac109f
Revises: 
Create Date: 2020-07-16 21:02:09.097648

"""
from alembic import op
import sqlalchemy as sa
import airflow
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7b25fac109f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dagen_dag',
    sa.Column('dag_id', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('live_version', sa.Integer(), nullable=True),
    sa.Column('created_at', airflow.utils.sqlalchemy.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', airflow.utils.sqlalchemy.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('dag_id')
    )
    op.create_index(op.f('ix_dagen_dag_created_at'), 'dagen_dag', ['created_at'], unique=False)
    op.create_index(op.f('ix_dagen_dag_updated_at'), 'dagen_dag', ['updated_at'], unique=False)
    op.create_table('dagen_dag_version',
    sa.Column('dag_id', sa.String(length=250), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dag_options', sa.Text(), nullable=False),
    sa.Column('created_at', airflow.utils.sqlalchemy.UtcDateTime(timezone=True), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('approver', sa.Integer(), nullable=True),
    sa.Column('approved_at', airflow.utils.sqlalchemy.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver'], ['ab_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator'], ['ab_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dag_id'], ['dagen_dag.dag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dag_id', 'version')
    )
    op.create_index(op.f('ix_dagen_dag_version_approved_at'), 'dagen_dag_version', ['approved_at'], unique=False)
    op.create_index(op.f('ix_dagen_dag_version_created_at'), 'dagen_dag_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_dagen_dag_version_dag_id'), 'dagen_dag_version', ['dag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dagen_dag_version_dag_id'), table_name='dagen_dag_version')
    op.drop_index(op.f('ix_dagen_dag_version_created_at'), table_name='dagen_dag_version')
    op.drop_index(op.f('ix_dagen_dag_version_approved_at'), table_name='dagen_dag_version')
    op.drop_table('dagen_dag_version')
    op.drop_index(op.f('ix_dagen_dag_updated_at'), table_name='dagen_dag')
    op.drop_index(op.f('ix_dagen_dag_created_at'), table_name='dagen_dag')
    op.drop_table('dagen_dag')
    # ### end Alembic commands ###
