"""Added template_id in dagen dag

Revision ID: db3d3cc79285
Revises: b7b25fac109f
Create Date: 2020-07-17 12:06:36.309223

"""
from alembic import op
import sqlalchemy as sa
import airflow
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db3d3cc79285'
down_revision = 'b7b25fac109f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dagen_dag', sa.Column('template_id', sa.String(length=250), nullable=False))
    op.create_index(op.f('ix_dagen_dag_template_id'), 'dagen_dag', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dagen_dag_template_id'), table_name='dagen_dag')
    op.drop_column('dagen_dag', 'template_id')
    # ### end Alembic commands ###
